//Auto-generated by RSP Compiler
//Source: ../../private-area/index.rsp.html
part of devdactic;

/** Template, index, for rendering the view. */
Future index(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<!DOCTYPE html>
<html>
  <head>
    <title>devdactic code school</title>
  </head>
  <body>
  	<h1>Hello """); //#2

  response.write(Rsp.nnx(currentUser(request.session) != null ? currentUser(request.session): "Stranger")); //#8


  response.write("""</h1>
    <p>You have successful logged in!</p>
    <p><a href="/s_logout">Sign out</a></p>
  </body>
</html>


"""); //#8

  return new Future.value();
}
