//Auto-generated by RSP Compiler
//Source: index.rsp.html
part of devdactic;

/** Template, index, for rendering the view. */
Future index(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<!DOCTYPE html>
<html>
  <head>
    <title>devdactic code school</title>
  </head>
  <body>
    <h1>Everything works, yeaah!</h1>
  </body>
</html>"""); //#2

  return new Future.value();
}
