//Auto-generated by RSP Compiler
//Source: home.rsp.html
part of devdactic;

/** Template, home, for rendering the view. */
Future home(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<!DOCTYPE html>
<html>
  <head>
    <title>devdactic code school</title>
    
    <link href="packages/bootjack/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/signin/signin.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">
    
      <form class="form-signin" role="form" action="/s_login" method="post">
        <h2 class="form-signin-heading">Please sign in</h2>
        
"""); //#2

  if (request.uri.queryParameters["error"] != null) { //if#16

    response.write("""    <div class="error">Incorrect username or password.</div>
"""); //#17
  } //if

  response.write("""    
        <input name="s_username" type="text" class="form-control" placeholder="Username" required autofocus>
        <input name="s_password" type="password" class="form-control" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <br>For testing: beginner/1337 ; admin/1337
      </form>
      
    </div>
  </body>
</html>"""); //#19

  return new Future.value();
}
